"""
tools/cases.py -- the corpus case definitions (single source of truth for make_expected.py,
make_manifest.py and, in Phase 4, the runner).

Tiers: 'stable'  = source whose bytes should not change over time (gp-first.php, records.php for
                    old objects, derived files, vectors) -> frozen expected values, checksum-verifiable;
       'live'    = rolling/live query -> our snapshot's values are a dated reference; the runner
                    applies structural checks to whatever the user fetched.
"""

F = "fixtures"


def gp(prefix, exts):
    return [f"{prefix}.{e}" for e in exts]


ALL5 = ["tle", "csv", "json", "xml", "kvn"]
ALL7 = ["tle", "2le", "csv", "json", "pretty.json", "xml", "kvn"]

CHECKS = {
    "omm-formats-agree": "For the same object and snapshot, CSV, JSON, XML and KVN yield identical canonical values for every OMM keyword present in all of them.",
    "tle-values-match-omm-within-tle-precision": "The TLE rendering equals the OMM values except: eccentricity truncated to 7 digits, BSTAR and second derivative rounded (half up) to a 5-digit mantissa, epoch at 1e-8 day resolution.",
    "tle-checksums-valid": "Every TLE line 1 and line 2 is 69 characters and ends with the modulo-10 checksum (digits count their value, '-' counts 1, everything else 0).",
    "catalog-number-is-integer": "NORAD_CAT_ID parses as an integer in every OMM format, including values of six and nine digits, and a ten-digit value is rejected (CCSDS allows up to nine digits); leading zeros and an explicit '+' are legal in KVN.",
    "tle-catalog-field-decodes": "Columns 3-7 of TLE lines 1 and 2 decode to the same integer (five digits, or Alpha-5 letter + four digits).",
    "ccsds-epoch-strings": "parse_epoch accepts every CCSDS 502.0-B-3 7.5.10 epoch form in vectors/ccsds-epoch-strings.json (calendar and day-of-year, with or without a fraction and a Z, second 60) and returns the instant each denotes (within 2 us; a leap second may read as 23:59:59 or as the next midnight), and rejects the five invalid forms.",
    "two-digit-year-pivot": "TLE epoch years 57-99 map to 1957-1999 and 00-56 to 2000-2056; the resulting ISO epoch equals the OMM EPOCH string.",
    "object-id-may-be-empty": "OBJECT_ID (and in principle OBJECT_NAME) can be empty; parsers must not fail, and must not invent a value.",
    "object-name-unknown-literal": "OBJECT_NAME may be the literal UNKNOWN (CCSDS-recommended) rather than empty.",
    "csv-json-omit-constant-metadata": "CelesTrak CSV/JSON carry no CENTER_NAME, REF_FRAME, TIME_SYSTEM or MEAN_ELEMENT_THEORY; parsers must default them (EARTH, TEME, UTC, SGP4) rather than fail.",
    "xml-ndm-wrapper-omm-2.0": "CelesTrak XML has an <ndm> root containing one <omm> per record with id=CCSDS_OMM_VERS and version=2.0; CREATION_DATE and ORIGINATOR elements are present but empty.",
    "kvn-blank-mandatory-values": "CelesTrak KVN writes CREATION_DATE and ORIGINATOR with blank values and blank OBJECT_ID for analyst objects; MEAN_ELEMENT_THEORY is 'SGP/SGP4'.",
    "leading-dot-decimals": "CSV, KVN and XML values may start with '.' or '-.' (no leading zero) and use 'E' exponents; JSON carries numbers.",
    "tle-format-omits-ids-above-99999": "A TLE/3LE/2LE request returns only objects with catalog numbers below 100000; if none qualify the response is HTTP 404 'No GP data found'.",
    "tle-count-equals-omm-count-below-100000": "The number of TLE records equals the number of OMM records whose NORAD_CAT_ID < 100000 for the same query.",
    "nine-digit-ids-parse": "NORAD_CAT_ID values >= 100000000 parse and round-trip as integers in CSV, JSON, XML and KVN.",
    "supgp-extra-keys-tolerated": "SupGP CSV/JSON add non-OMM keys (RMS, DATA_SOURCE); parsers must ignore unknown keys rather than fail.",
    "classification-c": "CLASSIFICATION_TYPE may be 'C' (CelesTrak supplemental) rather than 'U'.",
    "element-set-zero-and-rev-one": "ELEMENT_SET_NO may be 0 and REV_AT_EPOCH may be 1 or 0.",
    "mmdot-is-tle-field-value": "OMM MEAN_MOTION_DOT equals the TLE first-derivative field as printed (the TLE 'ndot/2' convention); MEAN_MOTION_DDOT likewise equals the TLE second-derivative field.",
    "bstar-implied-decimal-exponent": "TLE BSTAR and second-derivative fields are +/-NNNNN+/-E with an implied leading decimal point: ' 15975-3' is 0.15975e-3; zero is written ' 00000+0'.",
    "negative-bstar-and-ndot": "BSTAR and the first derivative can be negative; parsers must keep the sign.",
    "alpha5-decode": "An Alpha-5 catalog field decodes as (letter value)*10000 + digits with A=10 ... Z=33 and I, O unused; 'I', 'O' and lowercase are invalid.",
    "alpha5-encode": "Integers 100000-339999 encode to the Alpha-5 table; below 100000 encode as five digits with leading zeros; above 339999 cannot be encoded.",
    "satcat-legacy-below-70000": "The legacy fixed-width SATCAT contains only NORAD ids below 70000; the CSV/JSON SATCAT contains ids on both sides.",
    "kvn-syntax-tolerance": "KVN parsers accept blank lines, COMMENT lines at allowed positions, arbitrary whitespace around '=', bracketed units, day-of-year epochs, an optional trailing Z, signed integers, lowercase 'e' exponents, LF or CRLF endings.",
    "optional-tle-parameters-may-be-absent": "EPHEMERIS_TYPE, CLASSIFICATION_TYPE, NORAD_CAT_ID, ELEMENT_SET_NO and REV_AT_EPOCH are Optional in CCSDS Table 4-3 and may be missing from a valid OMM.",
    "omm-version-3-accepted": "CCSDS_OMM_VERS 3.0 messages (with CLASSIFICATION and MESSAGE_ID in the header) are accepted alongside 2.0.",
    "sha256-matches-tested-snapshot": "If the user's fetched bytes hash to the recorded SHA-256, the frozen expected values apply exactly; otherwise only structural checks apply and the tool says so.",
    "tle-writer-catalog-field": "A TLE writer puts the catalog number in columns 3-7 of both lines as five digits with leading zeros below 100000 and, from 100000 to 339999, as Alpha-5 (letter value 10-33, A=10 ... Z=33 with I and O never used, then the last four digits); both lines carry the same field.",
    "tle-writer-round-trip": "The written lines, read back by the corpus reference reader, reproduce the record's epoch, mean motion, eccentricity, inclination, RA of ascending node, argument of pericenter, mean anomaly and BSTAR at each field's resolution, quantised by truncation or by rounding half up (CelesTrak truncates the eccentricity, Space-Track rounds it; either is accepted and the convention observed is reported).",
    "tle-writer-refuses-unencodable": "A TLE catalog field cannot represent a number above 339999 (Z9999) or below 0, so the correct output for such a record is a refusal: an error and no lines. Those numbers belong in the OMM formats. The check passes when the writer refuses and fails when it writes lines with a six-digit, blank or otherwise invalid field.",
    "tle-writer-secondary-fields": "Whether the writer preserves, zeroes or drops MEAN_MOTION_DOT, MEAN_MOTION_DDOT, ELEMENT_SET_NO, REV_AT_EPOCH, CLASSIFICATION_TYPE, OBJECT_ID and OBJECT_NAME, and which exponent sign it writes for a zero second derivative (CelesTrak +, Space-Track -). Reported for information, never failed: orbit-fitting tools regenerate these fields by design.",
    "tle-writer-column-layout": "Every field of a written TLE sits in its fixed columns: on line 1 the decimal points at columns 24 and 35 and the separators at 2, 9, 18, 33, 44, 53, 62 and 64; on line 2 the decimal points at 12, 21, 38, 47 and 55, the separators at 2, 8, 17, 26, 34, 43 and 52, seven eccentricity digits, right-justified element set and revolution numbers. A left-justified value with a recomputed checksum has the right length and checksum and still fails this check.",
    "tle-writer-matches-provider-rendering": "Per field, how many written fields are byte-identical to the provider's rendering of the same record (CelesTrak's TLE line, or the corpus's CelesTrak-style derived line). Information only: an equivalent rendering under the other provider's convention is not a defect.",
}

AMBIGUITIES = {
    "unknown-vs-blank": "CCSDS 502.0-B-3 Table 4-2 says an unknown OBJECT_NAME/OBJECT_ID 'should be set to UNKNOWN' and 7.5.1 requires a non-empty value for mandatory keywords; CelesTrak writes an empty OBJECT_ID (empty string in CSV/JSON/KVN, empty element in XML) while the first-ever analyst records carry OBJECT_NAME 'UNKNOWN'. The corpus expects the provider's actual output and records the spec text.",
    "empty-mandatory-header": "CCSDS Table 4-1 makes CREATION_DATE and ORIGINATOR mandatory; CelesTrak emits them empty in XML and blank in KVN. The 2.0 schema's epochType pattern accepts an empty string, so schema validation may pass; the KVN rule 7.5.1 is still violated.",
    "omm-version-2-vs-3": "CelesTrak declares OMM version 2.0 (Silver Book 2009) although the current standard is 3.0 (Blue Book 2023). The 2.0 XML schema set is still downloadable from SANA by direct URL; against the current 4.0.0/3.0 set the documents fail on the fixed version attribute.",
    "met-sgp-sgp4-vs-sgp4": "For the same record CelesTrak writes MEAN_ELEMENT_THEORY = SGP/SGP4 in KVN and SGP4 in XML. Both appear in CCSDS examples; parsers should accept both.",
    "leading-dot-decimals": "CCSDS 7.5.6 requires at least one digit before and after the decimal point in KVN fixed-point values; CelesTrak writes '.00048259' and '.15975118E-3'. Most decimal parsers accept this; strict KVN validators may not.",
    "mmdot-convention": "CCSDS 4.2.4.7 NOTE 2 says TLE-sourced MEAN_MOTION_DOT/DDOT 'need to be divided by 2 and 6 respectively' but does not say which convention the OMM value carries. Observed: CelesTrak's OMM values equal the TLE fields as printed (304/304 records), i.e. the halved / sixth-ed values. Parsers converting to true derivatives must multiply by 2 and 6.",
    "ecc-truncation-vs-mantissa-rounding": "CelesTrak's TLE rendering truncates eccentricity to 7 digits but rounds (half up) BSTAR and the second derivative to a 5-digit mantissa (304/304 CelesTrak records reproduced with these rules; 0 with the opposite rules). No document states either rule; treat as observed CelesTrak behaviour. It is not universal: in the owner's Space-Track verification run (D-070) Space-Track's TLE for the same epoch differed from the CelesTrak-rendered line in the last one or two eccentricity digits (columns 32-33), consistent with rounding, and wrote a zero second derivative as 00000-0 (column 51) where CelesTrak writes 00000+0.",
    "object-id-launch-year-pivot": "No document defines how a two-digit launch year in the TLE international designator maps to a century. The corpus applies the same 57 pivot as the epoch year (python-sgp4 export_omm does the same); CelesTrak's OMM OBJECT_ID carries four-digit years, so the mapping matters only for TLE input.",
    "tle-epoch-resolution": "The TLE epoch has 1e-8 day (864 microsecond) resolution. CelesTrak GP epochs convert exactly between the two representations; SupGP epochs do not (86 microsecond difference observed), so a TLE->OMM epoch comparison needs a tolerance of half the TLE resolution.",
    "supgp-extra-keys": "SupGP CSV/JSON carry RMS and DATA_SOURCE, which are not OMM keywords (CCSDS 7.9.2.2 allows only Table 4-x keywords in an OMM); CelesTrak's CSV/JSON are OMM-keyword-based formats, not OMM instances, so this is a format extension rather than a violation. Parsers must tolerate unknown keys.",
    "gp-first-stability": "The corpus assumes CelesTrak's gp-first.php ('first GP data available') returns the same record for a given catalog number indefinitely. This was not verified over time. tools/fetch.py compares every fetched file with the SHA-256 recorded in manifest.json after each run (and on demand with --check-drift) and prints a DRIFT line for any stable-tier source whose bytes differ; the runner independently labels such a source 'live' and stops applying the frozen values to it. Related observation (D-070, D-074): gp-first records are historical in their elements but can carry metadata assigned after first publication. For catalog 100000, Space-Track's earliest record has a blank international designator, Space-Track's current record carries the same designator as CelesTrak, and CelesTrak's gp-first record shows that designator back-filled; the line-2 elements are identical. Treat OBJECT_NAME and OBJECT_ID in a gp-first record as current metadata, not as the values first published.",
    "analyst-number-reuse": "Space-Track states analyst numbers 'can be constantly reused for different objects'; gp-first.php for an analyst id therefore returns whichever object first carried that number, which may differ from the object currently using it.",
    "satcat-record-drift": "SATCAT records for existing objects change when an object decays or its orbit summary is updated; records.php sources are treated as live for checksum purposes even though most fields are stable.",
    "supgp-redistribution": "SupGP data derives from operator-provided data (some explicitly 'with permission' to CelesTrak). Under the corpus design no raw bytes are shipped; the snapshot values for one SupGP record are published as a dated reference and may be removed by the owner before publication.",
}

CASES = [
    {
        "id": "epoch-year-19xx",
        "title": "ISS first GP record (1998): two-digit epoch year 98, seven renderings of one record",
        "kind": "gp",
        "sets": {"iss-first": {"tier": "stable", "files": gp(f"{F}/epoch-year-19xx/raw/iss-first", ALL7)}},
        "tests": ["2-digit-epoch-year", "same-object-all-formats", "bstar-implicit-decimal", "negative-ndot", "nonzero-nddot"],
        "checks": ["omm-formats-agree", "tle-values-match-omm-within-tle-precision", "tle-checksums-valid", "two-digit-year-pivot",
                   "csv-json-omit-constant-metadata", "xml-ndm-wrapper-omm-2.0", "kvn-blank-mandatory-values", "leading-dot-decimals",
                   "negative-bstar-and-ndot", "sha256-matches-tested-snapshot"],
        "coverage": {"provides": ["two-digit year in the 57-99 branch (98 -> 1998)", "negative first derivative", "non-zero second derivative (11563-4)", "BSTAR zero written 00000+0", "element set number 1, revolution number 0"],
                     "gaps": ["the 00-56 branch is covered only by 2026 records elsewhere; no record near the 56/57 boundary exists"]},
        "ambiguities": ["mmdot-convention", "empty-mandatory-header", "leading-dot-decimals", "met-sgp-sgp4-vs-sgp4", "omm-version-2-vs-3", "gp-first-stability"],
    },
    {
        "id": "baseline-iss-five-formats",
        "title": "ISS current GP record: the same object in TLE, 2LE, CSV, JSON, JSON-PRETTY, XML and KVN (live)",
        "kind": "gp",
        "sets": {"iss-live": {"tier": "live", "files": gp(f"{F}/baseline-iss-five-formats/raw/iss", ALL7)}},
        "tests": ["same-object-all-formats", "2-digit-epoch-year", "bstar-implicit-decimal"],
        "checks": ["omm-formats-agree", "tle-values-match-omm-within-tle-precision", "tle-checksums-valid", "two-digit-year-pivot",
                   "csv-json-omit-constant-metadata", "xml-ndm-wrapper-omm-2.0", "kvn-blank-mandatory-values", "leading-dot-decimals"],
        "coverage": {"provides": ["a current 5-digit object in every rendering", "eccentricity with 8 OMM digits truncated to 7 in the TLE", "BSTAR with 8 OMM digits rounded to 5 in the TLE"],
                     "gaps": ["live source: a user's fetch returns a different epoch; only structural checks apply unless the SHA-256 matches"]},
        "ambiguities": ["ecc-truncation-vs-mantissa-rounding", "mmdot-convention"],
    },
    {
        "id": "six-digit-omm-saramago",
        "title": "Catalog number 100000 (SARAMAGO): first 6-digit object, OMM formats only, TLE unavailable",
        "kind": "gp",
        "sets": {"saramago-first": {"tier": "stable", "files": gp(f"{F}/six-digit-omm-saramago/raw/saramago-first", ALL5)},
                 "saramago-live": {"tier": "live", "files": gp(f"{F}/six-digit-omm-saramago/raw/saramago", ["csv", "json", "xml", "kvn", "tle"])},
                 "saramago-satcat": {"tier": "live", "kind": "satcat", "files": [f"{F}/six-digit-omm-saramago/raw/saramago.satcat.json", f"{F}/six-digit-omm-saramago/raw/saramago.satcat.csv"]}},
        "tests": ["6-digit-catalog-number", "tle-unavailable-above-99999", "same-object-all-omm-formats"],
        "checks": ["catalog-number-is-integer", "omm-formats-agree", "tle-format-omits-ids-above-99999", "csv-json-omit-constant-metadata", "xml-ndm-wrapper-omm-2.0", "sha256-matches-tested-snapshot"],
        "coverage": {"provides": ["the first 6-digit catalog number, stable (gp-first) and live", "HTTP 404 'No GP data found' for the TLE request, stable and live", "SATCAT record verifying designator 2026-067CY and launch 2026-03-30"],
                     "gaps": ["only one object; other 6-digit objects are in last-30-days and analyst cases"]},
        "ambiguities": ["gp-first-stability", "satcat-record-drift"],
    },
    {
        "id": "tle-omits-six-digit-objects",
        "title": "A group with only 6-digit objects: OMM formats return 256 records, the TLE request returns HTTP 404",
        "kind": "gp",
        "sets": {"last-30-days": {"tier": "live", "files": [f"{F}/tle-omits-six-digit-objects/raw/last-30-days.csv", f"{F}/tle-omits-six-digit-objects/raw/last-30-days.tle", f"{F}/tle-omits-six-digit-objects/raw/last-30-days-recapture.tle"]}},
        "tests": ["tle-unavailable-above-99999", "6-digit-catalog-number"],
        "checks": ["tle-format-omits-ids-above-99999", "tle-count-equals-omm-count-below-100000", "catalog-number-is-integer"],
        "coverage": {"provides": ["256 six-digit ids 100404-100789 in CSV", "TLE request -> 404 with body 'No GP data found' (captured twice: at 00:10Z, when a tool defect discarded the body and it was reconstructed by hand from the tool's log, D-013; and at 00:41Z as a clean re-capture with full headers, D-022)", "11 records with non-zero second derivative", "negative BSTAR values"],
                     "gaps": ["window-dependent: once objects below 100000 re-enter the 30-day window the TLE request will return data again; the structural check covers both outcomes"]},
        "ambiguities": [],
    },
    {
        "id": "analyst-objects",
        "title": "Analyst objects: empty OBJECT_ID, OBJECT_NAME UNKNOWN, 8xxxx and 27xxxx ids, TLE keeps only the 5-digit ones",
        "kind": "gp",
        "sets": {"analyst-live": {"tier": "live", "files": gp(f"{F}/analyst-objects/raw/analyst", ALL5) + [f"{F}/analyst-objects/raw/analyst-recapture.tle"]},
                 "analyst-270449-first": {"tier": "stable", "files": gp(f"{F}/analyst-objects/raw/analyst-270449-first", ALL5)},
                 "analyst-81011-first": {"tier": "stable", "files": gp(f"{F}/analyst-objects/raw/analyst-81011-first", ["tle", "csv", "json"])}},
        "tests": ["analyst-objects-no-object-id", "6-digit-catalog-number", "tle-unavailable-above-99999"],
        "checks": ["object-id-may-be-empty", "object-name-unknown-literal", "catalog-number-is-integer", "tle-format-omits-ids-above-99999",
                   "tle-count-equals-omm-count-below-100000", "omm-formats-agree", "xml-ndm-wrapper-omm-2.0", "kvn-blank-mandatory-values"],
        "coverage": {"provides": ["565 analyst objects (219 in 80000-89999, 346 in 270000-270449) at the snapshot", "563 of 565 with an empty OBJECT_ID; all 565 carry the literal OBJECT_NAME 'UNKNOWN' (no analyst object in the group has a real name)", "stable first records for 270449 (6-digit, letter T) and 81011, also with OBJECT_NAME UNKNOWN and empty OBJECT_ID", "TLE rendering of the 81011 record with eight blank international-designator columns"],
                     "gaps": ["no analyst record with an empty OBJECT_NAME was observed; that variant is untested", "the 90000 block is not observed"]},
        "ambiguities": ["unknown-vs-blank", "analyst-number-reuse", "gp-first-stability"],
    },
    {
        "id": "nine-digit-supgp-launch-nominals",
        "title": "Nine-digit catalog numbers: launch nominals of the 18th Space Defense Squadron (18 SDS), 7995016xx, in CelesTrak SupGP data",
        "kind": "gp",
        "sets": {"starlink-38381": {"tier": "live", "files": gp(f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-38381-799501621", ["csv", "json", "xml", "kvn", "tle"])},
                 "starlink-all": {"tier": "live", "files": [f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-all.csv"], "record_filter": "nine-digit"}},
        "tests": ["9-digit-catalog-number", "tle-unavailable-above-99999"],
        "checks": ["nine-digit-ids-parse", "catalog-number-is-integer", "omm-formats-agree", "tle-format-omits-ids-above-99999", "supgp-extra-keys-tolerated", "classification-c"],
        "coverage": {"provides": ["one 9-digit object (799501621) in CSV, JSON, XML and KVN; TLE request -> 404 'No SupGP data found'", "27 nine-digit ids 799501621-799501647 in the full Starlink SupGP file at the snapshot"],
                     "gaps": ["perishable: nominals exist only for roughly 5-8 days after a launch (CelesTrak); a user's fetch may contain none, in which case the check nine-digit-ids-parse reports not-exercised rather than failing", "no 9-digit id exists in 18 SDS GP data; only SupGP"]},
        "ambiguities": ["supgp-extra-keys", "supgp-redistribution", "tle-epoch-resolution"],
    },
    {
        "id": "supgp-celestrak-classification-c",
        "title": "CelesTrak supplemental GP: classification C, element set 0, RMS/DATA_SOURCE columns, 72000-series ids",
        "kind": "gp",
        "sets": {"starlink-g15-27": {"tier": "live", "files": gp(f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-g15-27", ["csv", "json", "xml", "kvn", "tle"])}},
        "tests": ["supgp-extra-fields", "classification-c"],
        "checks": ["supgp-extra-keys-tolerated", "classification-c", "element-set-zero-and-rev-one", "omm-formats-agree", "tle-values-match-omm-within-tle-precision", "tle-checksums-valid"],
        "coverage": {"provides": ["two SupGP records (stack 72000 and single 72001) in five formats", "TLE epoch rounded to 1e-8 day (86 us from the CSV epoch)", "OBJECT_ID 2026-219A shared by the stack nominal and a per-satellite nominal (799501621)"],
                     "gaps": ["perishable: this post-deployment file is replaced after cataloguing", "the meaning of the 72000-series ids (the 70000-79999 block) is described only by a secondary source (RESEARCH.md §1); primary sources cover only the 80000-89999 analyst range and the 69999 end of the legacy range"]},
        "ambiguities": ["supgp-extra-keys", "tle-epoch-resolution", "supgp-redistribution"],
    },
    {
        "id": "bstar-and-derivative-forms",
        "title": "Drag terms: negative BSTAR, negative first derivative, non-zero second derivative, implied-decimal exponent fields",
        "kind": "gp",
        "sets": {"decaying": {"tier": "live", "files": [f"{F}/bstar-and-derivative-forms/raw/decaying.tle", f"{F}/bstar-and-derivative-forms/raw/decaying.csv", f"{F}/bstar-and-derivative-forms/raw/decaying-recapture.tle"]},
                 "gp-69999-first": {"tier": "stable", "files": gp(f"{F}/satcat-70000-cutoff/raw/gp-69999-first", ["tle", "csv"])}},
        "tests": ["bstar-implicit-decimal", "negative-bstar", "negative-ndot", "nonzero-nddot"],
        "checks": ["bstar-implied-decimal-exponent", "negative-bstar-and-ndot", "mmdot-is-tle-field-value", "tle-values-match-omm-within-tle-precision", "tle-checksums-valid", "tle-count-equals-omm-count-below-100000"],
        "coverage": {"provides": ["79 decaying objects with non-zero second derivative", "negative BSTAR (69999: -70517-5) and negative first derivative", "BSTAR up to 0.0052 (51949-2)"],
                     "gaps": ["no BSTAR with a positive exponent (>= 1.0 Earth radii^-1) exists in any fetched data; that encoding ('NNNNN+1') is untested", "no second derivative with a positive exponent"]},
        "ambiguities": ["ecc-truncation-vs-mantissa-rounding", "mmdot-convention"],
    },
    {
        "id": "satcat-70000-cutoff",
        "title": "SATCAT on both sides of 70000: CSV/JSON records for 25544, 69999 and 100000; legacy fixed-width file stops at 69999",
        "kind": "satcat",
        "sets": {"satcat-records": {"tier": "live", "kind": "satcat", "files": [f"{F}/satcat-70000-cutoff/raw/satcat-25544.json", f"{F}/satcat-70000-cutoff/raw/satcat-25544.csv", f"{F}/satcat-70000-cutoff/raw/satcat-69999.json", f"{F}/satcat-70000-cutoff/raw/satcat-69999.csv", f"{F}/six-digit-omm-saramago/raw/saramago.satcat.json", f"{F}/six-digit-omm-saramago/raw/saramago.satcat.csv"]},
                 "satcat-legacy": {"tier": "live", "kind": "satcat-legacy", "files": [f"{F}/satcat-70000-cutoff/raw/satcat.txt"]}},
        "tests": ["legacy-satcat-cutoff-70000"],
        "checks": ["satcat-legacy-below-70000", "catalog-number-is-integer"],
        "coverage": {"provides": ["legacy file: 69,999 lines, ids 1..69999 contiguous, none >= 70000", "records.php JSON/CSV for 25544, 69999 (VANGUARD DEB, 1958-002D) and 100000"],
                     "gaps": ["the 9.4 MB legacy file is not shipped; users fetch it once and the check recomputes the facts"]},
        "ambiguities": ["satcat-record-drift"],
    },
    {
        "id": "csv-json-omitted-mandatory-fields",
        "title": "CelesTrak CSV and JSON omit the constant mandatory metadata keywords",
        "kind": "facts",
        "sets": {"all-csv-json": {"tier": "mixed", "files": [
            f"{F}/epoch-year-19xx/raw/iss-first.csv", f"{F}/epoch-year-19xx/raw/iss-first.json", f"{F}/baseline-iss-five-formats/raw/iss.csv", f"{F}/baseline-iss-five-formats/raw/iss.json",
            f"{F}/six-digit-omm-saramago/raw/saramago-first.csv", f"{F}/six-digit-omm-saramago/raw/saramago-first.json", f"{F}/analyst-objects/raw/analyst.csv", f"{F}/analyst-objects/raw/analyst.json",
            f"{F}/tle-omits-six-digit-objects/raw/last-30-days.csv", f"{F}/bstar-and-derivative-forms/raw/decaying.csv", f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-38381-799501621.csv", f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-38381-799501621.json"]}},
        "tests": ["csv-json-defaults"],
        "checks": ["csv-json-omit-constant-metadata", "supgp-extra-keys-tolerated"],
        "coverage": {"provides": ["every CelesTrak CSV/JSON file lacks CENTER_NAME, REF_FRAME, TIME_SYSTEM, MEAN_ELEMENT_THEORY and the header keywords", "SupGP files add RMS and DATA_SOURCE"], "gaps": []},
        "ambiguities": ["supgp-extra-keys"],
    },
    {
        "id": "mean-motion-derivative-convention",
        "title": "MEAN_MOTION_DOT / MEAN_MOTION_DDOT in the OMM equal the TLE fields as printed",
        "kind": "pairs",
        "pairs": [(f"{F}/epoch-year-19xx/raw/iss-first.tle", f"{F}/epoch-year-19xx/raw/iss-first.csv"), (f"{F}/baseline-iss-five-formats/raw/iss.tle", f"{F}/baseline-iss-five-formats/raw/iss.csv"),
                  (f"{F}/analyst-objects/raw/analyst.tle", f"{F}/analyst-objects/raw/analyst.csv"), (f"{F}/analyst-objects/raw/analyst-81011-first.tle", f"{F}/analyst-objects/raw/analyst-81011-first.csv"),
                  (f"{F}/bstar-and-derivative-forms/raw/decaying.tle", f"{F}/bstar-and-derivative-forms/raw/decaying.csv"), (f"{F}/satcat-70000-cutoff/raw/gp-69999-first.tle", f"{F}/satcat-70000-cutoff/raw/gp-69999-first.csv"),
                  (f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-g15-27.tle", f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-g15-27.csv")],
        "tests": ["mmdot-convention"],
        "checks": ["mmdot-is-tle-field-value"],
        "coverage": {"provides": ["304 TLE/OMM record pairs compared"], "gaps": ["no record with a non-zero second derivative whose OMM text has more than 5 significant digits was observed, so the DDOT comparison is exact-equality only"]},
        "ambiguities": ["mmdot-convention"],
    },
    {
        "id": "tle-vs-omm-precision-loss",
        "evidence_basis": [
            "The rendering rule stated by this case (eccentricity truncated to 7 digits; BSTAR and second-derivative mantissa rounded half up to 5 digits) was derived empirically from a sample of 304 CelesTrak TLE/OMM record pairs fetched 2026-09-21 (219 analyst, 79 decaying, 2 SupGP, 4 single objects). It is not documented in any specification or provider document we located (CCSDS 502.0-B-3, CelesTrak TLE format documentation, Space-Track TLE documentation); it is observed provider behaviour, and the sample is what supports it.",
            "With these rules the renderer in gpconf/tle.py reproduced 304 of 304 records byte for byte; with eccentricity rounded instead, 257 of 304; with the mantissa truncated instead, 251 of 304.",
            "The rule is CelesTrak's, not the TLE format's. Space-Track rounds the eccentricity: confirmed by prediction (D-071). From the CelesTrak OMM sources of the 21 records whose epochs matched in the owner's Space-Track run, rounding to 7 digits differs from truncation for exactly 8 (T0000, T0003, T0008, T0011, T0016, T0018, T0020, T0449; three of them with a carry into the sixth digit), and exactly those 8 Space-Track lines differed from the CelesTrak-rendered lines at column 33 (the three carries at columns 32-33); the other 13, where rounding equals truncation, matched. All 21 derived lines carry a zero second derivative, so the column-51 difference present on every one of them is the +0 (CelesTrak) versus -0 (Space-Track) sign of that field. A parser comparing a TLE to its OMM must therefore know which provider rendered the TLE.",
        ],
        "title": "The TLE is a lossy rendering of the OMM record: eccentricity truncated, BSTAR/DDOT mantissa rounded, epoch quantised",
        "kind": "pairs",
        "pairs": None,  # same pairs as mean-motion-derivative-convention
        "tests": ["precision-loss", "round-trip-lossiness"],
        "checks": ["tle-values-match-omm-within-tle-precision"],
        "coverage": {"provides": ["eccentricity: OMM has up to 8 decimals, TLE keeps the first 7 (truncation)", "BSTAR / DDOT: OMM has up to 8 significant digits, TLE keeps 5, rounded half up", "epoch: GP records convert exactly; SupGP records differ by up to half the 864 us TLE resolution", "TLE -> OMM -> TLE round trip through these rules is byte-exact (tests/test_roundtrip.py, every CelesTrak TLE record in the corpus plus the 604 derived lines)"],
                     "gaps": ["no rounding tie (mantissa digit 6 exactly 5 followed by zeros) was observed, so half-up versus half-even at the tie is not distinguished", "the 24-character limit of TLE line 0 is a rule of the CelesTrak format document, not an observation: no name longer than 24 characters occurs in the 304 provider pairs; the cut appears only in one derived line (catalog 100465)"]},
        "ambiguities": ["ecc-truncation-vs-mantissa-rounding", "tle-epoch-resolution"],
    },
    {
        "id": "omm-xml-schema",
        "title": "CelesTrak OMM XML against the SANA schemas: valid as NDM/XML 2.0, invalid as 3.0 on the version attribute",
        "kind": "xml",
        "files": [f"{F}/epoch-year-19xx/raw/iss-first.xml", f"{F}/baseline-iss-five-formats/raw/iss.xml", f"{F}/six-digit-omm-saramago/raw/saramago-first.xml", f"{F}/six-digit-omm-saramago/raw/saramago.xml",
                  f"{F}/analyst-objects/raw/analyst.xml", f"{F}/analyst-objects/raw/analyst-270449-first.xml", f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-38381-799501621.xml", f"{F}/nine-digit-supgp-launch-nominals/raw/starlink-g15-27.xml"],
        "tests": ["xml-schema"],
        "checks": ["xml-ndm-wrapper-omm-2.0", "omm-version-3-accepted"],
        "coverage": {"provides": ["8 XML files validated against ndmxml-2.0.0 and ndmxml-4.0.0"], "gaps": ["no CelesTrak XML with units attributes, comments or covariance exists; those constructs are covered only by the CCSDS examples and derived variants"]},
        "ambiguities": ["omm-version-2-vs-3", "empty-mandatory-header"],
    },
    {
        "id": "alpha5-encoding-vectors",
        "title": "Specification vectors: the Alpha-5 table with boundaries and invalid inputs, catalog-id text forms, the two-digit-year pivot and CCSDS epoch strings",
        "kind": "vectors",
        "files": ["vectors/alpha5.json", "vectors/norad-cat-id-text.json", "vectors/two-digit-epoch-year.json", "vectors/ccsds-epoch-strings.json"],
        "tests": ["alpha5-letter-skip-rules", "alpha5-range", "9-digit-catalog-number", "2-digit-epoch-year"],
        "checks": ["alpha5-decode", "alpha5-encode", "catalog-number-is-integer", "two-digit-year-pivot", "ccsds-epoch-strings"],
        "coverage": {"provides": ["Alpha-5: all 24 letters and both skips, the six official examples, range boundaries, invalid letters and lowercase",
                                  "catalog-id text forms: eight valid values (two of nine digits) and four to reject (Alpha-5 text, ten digits, a decimal, empty)",
                                  "the two-digit-year pivot: 57-99 to 1957-1999, 00-56 to 2000-2056",
                                  "CCSDS epoch strings: eight valid forms, each with the instant it denotes, and five invalid forms"],
                     "gaps": ["vectors are not element sets; they test the mappings only"]},
        "ambiguities": [],
    },
    {
        "id": "alpha5-tle-derived",
        "evidence_basis": [
            "The renderer that produced these lines applies a rendering rule (eccentricity truncated to 7 digits; BSTAR and second-derivative mantissa rounded half up to 5 digits) that was derived empirically from 304 CelesTrak TLE/OMM record pairs and is not documented in any specification we located. See case tle-vs-omm-precision-loss.",
            "The renderer was validated only against CelesTrak output for catalog numbers below 100000, because CelesTrak emits no Alpha-5 TLE at all. The Alpha-5 encoding step itself is corroborated by python-sgp4's independent implementation (all 604 derived lines decode to the source catalog number) and by the official Space-Track vectors.",
            "Provider corroboration of the encoding (D-070): on 2026-09-21 the project owner ran tools/verify_against_spacetrack.py against their own Space-Track account (44 records: current GP for 100000-100020 and 270000-270020, and the first historical record of 100000 and of 270449). Zero defects: every Alpha-5 field decoded to the queried catalog number, every line-2 field equalled line 1, and both observed letters (A and T) matched the derived encoding; where epochs matched, the international designator and elements agreed. No line was byte-identical, for rendering reasons that are not encoding differences: Space-Track writes a zero second derivative as 00000-0 (column 51, plus the checksum) where CelesTrak writes 00000+0, and Space-Track's line-2 eccentricity differs in its last one or two digits (columns 32-33) from CelesTrak's truncated rendering. No Space-Track data is in this repository; this paragraph describes the verification, not the data.",
        ],
        "title": "Derived Alpha-5 TLE lines rendered from real CelesTrak OMM records (letters A and T)",
        "kind": "derived-tle",
        "sets": {"derived": {"tier": "stable", "files": ["derived/alpha5-tle/alpha5-A-100000-saramago-first.tle", "derived/alpha5-tle/alpha5-T-270449-analyst-first.tle", "derived/alpha5-tle/alpha5-A-last-30-days-snapshot.tle", "derived/alpha5-tle/alpha5-T-analyst-27xxxx-snapshot.tle"]}},
        "tests": ["alpha5-tle-parsing", "alpha5-letter-skip-rules"],
        "checks": ["alpha5-decode", "tle-catalog-field-decodes", "tle-checksums-valid", "tle-values-match-omm-within-tle-precision"],
        "coverage": {"provides": ["604 Alpha-5 lines: 257 with letter A (ids 100000-100789), 347 with letter T (ids 270000-270449)"],
                     "gaps": ["letters B-H, J-N, P-S and U-Z appear in no real catalog number yet (the catalog is at ~100789 and the only other 6-digit block is 27xxxx); those letters are covered by vectors only",
                              "these lines are derived, not provider output: CelesTrak serves no Alpha-5 and Space-Track data is not used",
                              "renderer validation gap: the byte-for-byte validation (304/304) used only sub-100000 CelesTrak output, because CelesTrak emits no Alpha-5. The encoding step has since been corroborated against Space-Track output by the project owner (D-070: 44 records, 0 defects, letters A and T), but the derived lines are CelesTrak-style renderings and differ from Space-Track's own TLE lines in two conventions (zero second-derivative sign at column 51; eccentricity rounding versus truncation at columns 32-33), so they are not byte-identical to Space-Track output. No Space-Track data enters this repository; the public claim describes that verification, not the data."]},
        "ambiguities": ["ecc-truncation-vs-mantissa-rounding"],
    },
    {
        "id": "kvn-syntax-variants",
        "title": "CCSDS-legal KVN renderings of one record that CelesTrak never emits",
        "kind": "derived-kvn",
        "base": f"{F}/epoch-year-19xx/raw/iss-first.csv",
        "sets": {"variants": {"tier": "stable", "files": [f"derived/kvn-variants/{v}.kvn" for v in ["v01-baseline-reserialised", "v02-day-of-year-epoch-Z", "v03-units-brackets-leading-zeros", "v04-comments-blank-lines-whitespace-LF", "v05-omm-3.0-header-optional-keywords-omitted", "v06-signed-integers-lowercase-exponent"]]}},
        "tests": ["kvn-syntax"],
        "checks": ["kvn-syntax-tolerance", "optional-tle-parameters-may-be-absent", "omm-version-3-accepted"],
        "coverage": {"provides": ["day-of-year epoch with Z", "bracketed units", "COMMENT and blank lines, irregular whitespace, TAB, LF endings", "OMM 3.0 header with optional TLE parameters omitted", "signed integers and lowercase exponent"],
                     "gaps": ["lowercase normative text values (7.5.3) and the 254-character line limit are not exercised", "no XML variants in this version"]},
        "ambiguities": ["leading-dot-decimals", "met-sgp-sgp4-vs-sgp4"],
    },
    {
        # Writer-side case (added after v0.1.0; DECISIONS D-095..D-097). Must stay last: it reads the other
        # cases' expected.json files, which make_expected.py writes earlier in the same run.
        "id": "tle-writer-alpha5",
        "evidence_basis": [
            "Inputs are records already frozen in this corpus (the v0.1.0 expected values of stable-tier sources): the 604 derived Alpha-5 records (603 distinct ids, letters A and T), the first ISS record (1998 epoch, negative first derivative, non-zero second derivative, zero BSTAR), the first record of 69999 (negative BSTAR and first derivative) and the first record of analyst 81011 (blank international designator, empty OBJECT_ID). No new provider request and no new raw bytes.",
            "Three inputs are synthetic-derived (PLAN.md section 2.1; owner approval 2026-09-22, DECISIONS D-096): the SARAMAGO first record with NORAD_CAT_ID replaced by 340000, 799501621 and -1, the values of vectors/alpha5.json encode_unrepresentable. The elements are real; the ids are specification vectors that no catalogued object carries. The correct output for them is a refusal.",
            "The precision rule (a written field equals the input quantised at the field's resolution by truncation or by rounding half up) rests on the evidence of tle-vs-omm-precision-loss: CelesTrak truncates the eccentricity and rounds the mantissas (304/304 records), Space-Track rounds the eccentricity (D-070, D-071). A writer may follow either provider; the corpus reports which convention it observed.",
        ],
        "title": "Writing TLEs across the five-digit boundary: Alpha-5 catalog field, valid lines, refusal of numbers the format cannot carry, round trip",
        "kind": "writer",
        "inputs_from": [
            {"case": "alpha5-tle-derived"},
            {"case": "epoch-year-19xx", "set": "iss-first"},
            {"case": "bstar-and-derivative-forms", "set": "gp-69999-first"},
            {"case": "analyst-objects", "set": "analyst-81011-first"},
        ],
        "unrepresentable": {"from_case": "six-digit-omm-saramago", "set": "saramago-first", "vectors": "vectors/alpha5.json"},
        "tests": ["alpha5-tle-writing", "alpha5-range", "tle-checksum"],
        "checks": ["tle-checksums-valid", "tle-writer-catalog-field", "tle-writer-column-layout", "tle-writer-round-trip", "tle-writer-refuses-unencodable",
                   "tle-writer-secondary-fields", "tle-writer-matches-provider-rendering"],
        "coverage": {"provides": ["606 real records as writer inputs: 603 distinct Alpha-5 ids (257 with letter A, 346 with letter T; the 604 derived lines carry 270449 twice, from its first record and from the analyst snapshot) and three five-digit ids (25544 at a 1998 epoch, 69999, 81011)",
                                  "a 1998 epoch, a negative first derivative, a non-zero second derivative, zero and negative BSTAR, a blank international designator, an empty OBJECT_ID",
                                  "three numbers the TLE catalog field cannot represent (340000, 799501621, -1), for which the correct output is a refusal",
                                  "provider-rendered field substrings for the three five-digit records and the CelesTrak-style derived fields for the 604 Alpha-5 records, for an information-only byte comparison"],
                     "gaps": ["letters B-S and U-Z occur in no real catalog number; a writer's encoding of those letters is covered by the alpha5_encode vectors only",
                              "no input has a BSTAR or second derivative with a positive exponent",
                              "no rounding tie at the last kept digit occurs in the inputs, so half-up versus half-even rounding is not distinguished for writers either",
                              "no output of an external tool is shipped; strf's rffit was exercised only at function level outside this repository (DECISIONS D-097) and has no adapter because it is an interactive X11 program"]},
        "ambiguities": ["ecc-truncation-vs-mantissa-rounding"],
    },
]
